# Generated by Django 3.1.3 on 2020-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietgenerator', '0004_auto_20201121_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='portion_unit',
            field=models.CharField(default='g', max_length=10),
        ),
    ]
